name: Node.js CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm install
      - run: npm run build
      - name: Deploy to Server
        uses: AEnterprise/rsync-deploy@v1.0
        env:
        DEPLOY_KEY: ${{ secrets.SSH_KEY }}
        ARGS: -avz --delete --exclude='*.pyc'
        SERVER_PORT: "22"
        FOLDER: ./build/*
        SERVER_IP: ${{ secrets.SSH_HOST }}
        USERNAME: ${{ secrets.SSH_USERNAME }}
        SERVER_DESTINATION: /usr/share/nginx/html/
